# @MajoraGenerator({"force_generation": true})

sir_api_person_collection:
    path: /
    defaults:
        _controller: SirPartnerApiBundle:PersonApi:cget
    methods:
        - GET

sir_api_person_create:
    path: /
    defaults:
        _controller: SirPartnerApiBundle:PersonApi:post
    methods:
        - POST

sir_api_person_read:
    path: /{id}
    defaults:
        _controller: SirPartnerApiBundle:PersonApi:get
    requirements:
        id: \d+
    methods:
        - GET

sir_api_person_update:
    path: /{id}
    defaults:
        _controller: SirPartnerApiBundle:PersonApi:put
    requirements:
        id: \d+
    methods:
        - PUT

sir_api_person_delete:
    path: /{id}
    defaults:
        _controller: SirPartnerApiBundle:PersonApi:delete
    requirements:
        id: \d+
    methods:
        - DELETE
