# @MajoraGenerator({"register_doctrine_em": {"target": "/config/config.yml"}})
# @MajoraGenerator({"register_doctrine_em": {"em": "default"}})
# @MajoraGenerator({"register_doctrine_em": {"prefix": "Test2\\Test2\\Component\\Entity"}})
# @MajoraGenerator({"register_doctrine_em": {"bundle": "Test2Test2DalBundle"}})
# @MajoraGenerator({"register_doctrine_em": {"alias": "Test2Test2"}})

Test2\Test2\Component\Entity\Test2:
    type: entity
    repositoryClass: Test2\Test2\Component\Repository\Doctrine\Test2DoctrineRepository
    table: test2_test2_test2
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

        # your other Test2 properties here

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    # manyToOne:
    #     example:
    #         targetEntity: Example
    #         inversedBy: test2s
    #         joinColumn:
    #             name: example_id
    #             referencedColumnName: id

    # oneToMany:
    #     examples:
    #         targetEntity: Example
    #         mappedBy: test2
    #         cascade: ['persist', 'remove']

    # manyToMany:
    #     examples:
    #         targetEntity: Example
    #         joinTable:
    #             name: test2_test2_test2_example
    #             joinColumns:
    #                 test2_id:
    #                     referencedColumnName: id
    #             inverseJoinColumns:
    #                 example_id:
    #                     referencedColumnName: id
