# @MajoraGenerator({"force_generation": true})

acme_api_post_collection:
    path: /
    defaults:
        _controller: AcmeLvApiBundle:PostApi:cget
    methods:
        - GET

acme_api_post_create:
    path: /
    defaults:
        _controller: AcmeLvApiBundle:PostApi:post
    methods:
        - POST

acme_api_post_read:
    path: /{id}
    defaults:
        _controller: AcmeLvApiBundle:PostApi:get
    requirements:
        id: \d+
    methods:
        - GET

acme_api_post_update:
    path: /{id}
    defaults:
        _controller: AcmeLvApiBundle:PostApi:put
    requirements:
        id: \d+
    methods:
        - PUT

acme_api_post_delete:
    path: /{id}
    defaults:
        _controller: AcmeLvApiBundle:PostApi:delete
    requirements:
        id: \d+
    methods:
        - DELETE
