# @MajoraGenerator({"force_generation": true})

sir1_api_person2_collection:
    path: /
    defaults:
        _controller: Sir1Partner3ApiBundle:Person2Api:cget
    methods:
        - GET

sir1_api_person2_create:
    path: /
    defaults:
        _controller: Sir1Partner3ApiBundle:Person2Api:post
    methods:
        - POST

sir1_api_person2_read:
    path: /{id}
    defaults:
        _controller: Sir1Partner3ApiBundle:Person2Api:get
    requirements:
        id: \d+
    methods:
        - GET

sir1_api_person2_update:
    path: /{id}
    defaults:
        _controller: Sir1Partner3ApiBundle:Person2Api:put
    requirements:
        id: \d+
    methods:
        - PUT

sir1_api_person2_delete:
    path: /{id}
    defaults:
        _controller: Sir1Partner3ApiBundle:Person2Api:delete
    requirements:
        id: \d+
    methods:
        - DELETE
