# @MajoraGenerator({"include_routing": {"target": "@SirPartnerApiBundle/Resources/config/routing.yml"}})
# @MajoraGenerator({"include_routing": {"route": "sir_partner_api"}})
# @MajoraGenerator({"include_routing": {"resource": "@SirPartnerApiBundle/Resources/config/routing.yml"}})

sir_partner_sdk:
    resource: "@SirPartnerSdkBundle/Resources/config/routing.yml"

sir_partner_api:
    resource: "@SirPartnerApiBundle/Resources/config/routing.yml"
    