# @MajoraGenerator({"register_doctrine_em": {"target": "/config/config.yml"}})
# @MajoraGenerator({"register_doctrine_em": {"em": "default"}})
# @MajoraGenerator({"register_doctrine_em": {"prefix": "Acme\\Lv\\Component\\Entity"}})
# @MajoraGenerator({"register_doctrine_em": {"bundle": "AcmeLvDalBundle"}})
# @MajoraGenerator({"register_doctrine_em": {"alias": "AcmeLv"}})

Acme\Lv\Component\Entity\Post:
    type: entity
    repositoryClass: Acme\Lv\Component\Repository\Doctrine\PostDoctrineRepository
    table: acme_lv_post
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

        # your other Post properties here

        name:
            type: string
            column: name

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    # manyToOne:
    #     example:
    #         targetEntity: Example
    #         inversedBy: posts
    #         joinColumn:
    #             name: example_id
    #             referencedColumnName: id

    # oneToMany:
    #     examples:
    #         targetEntity: Example
    #         mappedBy: post
    #         cascade: ['persist', 'remove']

    # manyToMany:
    #     examples:
    #         targetEntity: Example
    #         joinTable:
    #             name: acme_lv_post_example
    #             joinColumns:
    #                 post_id:
    #                     referencedColumnName: id
    #             inverseJoinColumns:
    #                 example_id:
    #                     referencedColumnName: id
