# @MajoraGenerator({"force_generation": true})

test2_api_test2_collection:
    path: /
    defaults:
        _controller: Test2Test2ApiBundle:Test2Api:cget
    methods:
        - GET

test2_api_test2_create:
    path: /
    defaults:
        _controller: Test2Test2ApiBundle:Test2Api:post
    methods:
        - POST

test2_api_test2_read:
    path: /{id}
    defaults:
        _controller: Test2Test2ApiBundle:Test2Api:get
    requirements:
        id: \d+
    methods:
        - GET

test2_api_test2_update:
    path: /{id}
    defaults:
        _controller: Test2Test2ApiBundle:Test2Api:put
    requirements:
        id: \d+
    methods:
        - PUT

test2_api_test2_delete:
    path: /{id}
    defaults:
        _controller: Test2Test2ApiBundle:Test2Api:delete
    requirements:
        id: \d+
    methods:
        - DELETE
